services:
  selenium:
    container_name: selenium
    image: seleniarm/standalone-chromium
    restart: unless-stopped
    ports:
      - "4444:4444"
      - "7900:7900"
      - "5900:5900"
    shm_size: 2gb
  scraper-valen:
    container_name: scraper-valen
    image: andresramirez991228/smart-scraper:latest
    restart: unless-stopped
    depends_on:
      - selenium
    env_file:
      - .valen.env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/var/log
      - ./shared:/app/shared

  scraper-andres:
    container_name: scraper-andres
    image: andresramirez991228/smart-scraper:latest
    restart: unless-stopped
    depends_on:
      - scraper-valen
    env_file:
      - .andres.env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/var/log
      - ./shared:/app/shared

  watchTower:
    container_name: watchTower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true

