services:
  selenium:
    image: selenium/standalone-chrome
    restart: unless-stopped
    ports:
      - "4444:4444"
      - "7900:7900"
      - "5900:5900"
    shm_size: 2gb
  scraper-valen:
    build: .
    restart: unless-stopped
    depends_on:
      - selenium
    env_file:
      - .valen.env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/var/log
      - ./shared:/app/shared

  scraper-andres:
    build: .
    restart: unless-stopped
    depends_on:
      - scraper-valen
    env_file:
      - .andres.env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/var/log
      - ./shared:/app/shared

