services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "7900:7900"
      - "5900:5900"
    shm_size: 2gb
  scraper:
    build: .
    depends_on:
      - selenium
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/var/log

