name: Release Docker image to Docker Hub

# Launch action when a new release is created
on:
  release:
    types:
      - created

  # Image will be released on tag creation
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Tag for the docker image"
        required: true
        default: "latest"

jobs:
  build-and-push:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: Set Docker image tag
        id: vars
        run: |
          if [ "${{ github.event.release.tag_name }}" != "" ]; then
            echo "IMAGE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/smart-scraper:latest .

      - name: Release image on Docker Hub
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/smart-scraper:latest
